### ISSUE TITLE
Documentation: Include structure of object passed to onComplete function

### ISSUE THREAD

**Issue by JimSchofield** [codeBelt/generate-template-files#17]
Maybe either give an example or just lay out the schema of the response when you describe the onComplete function in the readme.

**Comment by codeBelt** [comment]
I have this in the readme. https://github.com/codeBelt/generate-template-files#api 

-   `onComplete` - `optional` Takes a callback function that is called once the file(s) have been outputted. A `IResults` object will be passed to the callback which has the following properties:
    -   `output.path` - The file(s) output path
    -   `output.filesAndFolders` - List of folder and filenames created
    -   `stringReplacers` - List of Replacer Slots; name and values entered during the setup process

Can you give me an example of what you are expecting?

**Comment by JimSchofield** [comment]
In general you might document the return types and structure for your IConfigItem in the readme.
