### ISSUE TITLE
Expose string utility functions as a parameter of the onComplete callback

### ISSUE THREAD

**Issue by JimSchofield** [codeBelt/generate-template-files#18]
I need to format the the slotValue using the string utility in this package inside the `onComplete` callback.

Maybe expose the utility functions so I can do it manually in the callback, or add the formatted string to the slots:

```
[
    {
        slot: '__test__',
        slotValue: 'string thing',
        formattedSlotValue: 'string-thing',
    }
    ...
]
```

**Comment by JimSchofield** [comment]
Alternatively, can you export the string utility class so one could manually import the utility and use it in the generate file?
```
import { StringUtility } from 'generate-template-files';
...
onComplete: (data) => {
    ...
    let formattedSlotValue  = StringUtility.toCase(KebabCase);
}
```

**Comment by JimSchofield** [comment]
Probably best to expose the utility...

**Comment by codeBelt** [comment]
#19
