### ISSUE TITLE
Multiply the entry and output

### ISSUE THREAD

**Issue by ychow** [codeBelt/generate-template-files#22]
how should i can set the `entry` is Array? and it could generator more than one file?

**Comment by codeBelt** [comment]
Would it need to have an array of `output` also? Can you explain the use case for an array of `entry` points? 

Right now you point the `entry.folderPath` to a folder directory. It will generator all the files inside of that folder. Check out the `examples` folder in this project for examples of generating more than one file and single files.

**Comment by codeBelt** [comment]
Closing because this issue has gone stale.
