### ISSUE TITLE
Description of the string replacers

### ISSUE THREAD

**Issue by marcocesarato** [codeBelt/generate-template-files#35]
Should be possibile add as feature the possibility to add on stringReplacers a description/label of the placeholder we have to replace and have something like this: 

`stringReplacers: [{description: "Model class name", value: "__model__"}]`

and then have on console something like:

`Insert model class name: `

This is just an idea but should be possibile?

**Comment by codeBelt** [comment]
I created a PR https://github.com/codeBelt/generate-template-files/pull/36 with your request. Waiting for feedback from other before merging in.

**Comment by marcocesarato** [comment]
Yes is perfect thank you

**Comment by codeBelt** [comment]
@marcocesarato This feature has been published. Please let me know if you have any issues.
