### ISSUE TITLE
stringReplacers should be mandatory even for command line usage

### ISSUE THREAD

**Issue by krambono** [codeBelt/generate-template-files#41]
Currently stringReplacers is optional for command line usage. If we force the user to have the stringReplacers and command line arguments be the same, we could implement stricter validation.

**Comment by codeBelt** [comment]
Yes, I do agree. Thanks for validating my code. I will work on this later today.

**Comment by codeBelt** [comment]
This issue is fixed here https://github.com/codeBelt/generate-template-files/pull/44 . Please review and give any feedback.
