### ISSUE TITLE
Any ideas/chances to run it with Arrays/Objects properly?

### ISSUE THREAD

**Issue by vini-guerrero** [codeBelt/generate-template-files#49]
Hi! I'm loving so far this package.
However, I'm still not sure if it is possible to generate the file I need from terminal 100% automated, because parts of it might include JSON objects and array, like this (example only):

`response: {
      200: {
        type: "object",
        properties: {
          status: { type: "string" },
          statusCode: { type: "integer" },
          data: {
            type: "array",
            items: {
              type: "object",
              properties: {
                // name: { type: "string" }
                // prompt in terminal for this json object
                // could be an array here as well...
              }
            }
          }
        }
      },`

Are there any recommendations to automate this?
Thanks in advance, best regards!

**Comment by vini-guerrero** [comment]
I've been trying to use some type of pattern "key/value", but it only runs after generation so far...

![image](https://user-images.githubusercontent.com/18181786/96335083-250b7980-104c-11eb-8cc5-2841a9c167b7.png)

**Comment by codeBelt** [comment]
I'm not 100% following what you are trying to do but you should build up the structure before sending it to `generateTemplateFilesCommandLine`.

```js
(async () => {
  const response = await axios.get('https://api.something.com');

  const items = someFunctionThatTakesTheResponseAndCreatesTheStructureForTheLibrary(response);

  generateTemplateFilesCommandLine(items);
})();
```

**Comment by vini-guerrero** [comment]
Actually the problem is that I need to use replacers that are objects/arrays, so I'm not sure exactly how to prompt continuously for them in console. One way of doing it I thought would be defining how many items in array before asking properties, but this is very limited solution...  I will try to think of a better one...
