### ISSUE TITLE
Is it possible to use CaseConverter per stringReplacers?

### ISSUE THREAD

**Issue by misterboe** [codeBelt/generate-template-files#55]
I want to do something like that:

```
    stringReplacers: [
      {question: 'Extension name', slot: '${extname}', case:'(pascalCase)'},
      {question: 'Content element name', slot: '${cename}', case:'(lowerCase)'},
      {question: 'Content element title', slot: '${cetitle}'},
      {question: 'Content element description', slot: '${cedescription}'},
    ],
```

Would that be possbile?

**Comment by codeBelt** [comment]
I have no plans to add a feature like that. Wherever you use `${extname}` you will have to add a suffix `${extname}(pascalCase)` convert the case. This makes is flexible so you can have different CaseConverters in your file(s).

Example: 
`${extname}(pascalCase)`, `${extname}(lowerCase)`, `${extname}(noCase)`, `${extname}`.

**Comment by misterboe** [comment]
Didn't get that - thats what i need. Thanks @codeBelt
