### ISSUE TITLE
Emitter-mixin deprecation warning

### ISSUE THREAD

**Issue by lhassis** [codeBelt/generate-template-files#70]
Using the package with node 16.x.x shows a DeprecationWarning from the emitter-mixin dependency. It is used by the recursive-copy dependency and it has been fixed on version 2.0.12 (lib is already on 2.0.13 version). Is it possible to upgrade this dependency version so the warning is eliminated?

Warning message
[DEP0128] DeprecationWarning: Invalid 'main' field in 'xxx\node_modules\emitter-mixin\package.json' of 'y'. Please either fix that or report it to the module author

**Comment by codeBelt** [comment]
Fixed in https://github.com/codeBelt/generate-template-files/releases/tag/v3.2.1
