### ISSUE TITLE
[Question] Is there a way to run a generate without the interactive cli?

### ISSUE THREAD

**Issue by michaelwarren1106** [codeBelt/generate-template-files#71]
I want to use this to just automatically create a bunch of templated files without needing any user input. I have a node script that i'm writing and i'd just like to run a function to generate the files without being asked about "which option would you like to template"? kind of thing? Is this possible?

**Comment by wenfangdu** [comment]
For future viewers, this feature is documented [here](https://github.com/codeBelt/generate-template-files#batch-usage).
